### ISSUE TITLE
Root folder for Temporal stuff

### ISSUE THREAD

**Issue by michael-rubel** [keepsuit/laravel-temporal#16]
Hi @cappuc 

Wouldn't it be better to have `Workflows` and `Activities` registered automatically/placed by artisan commands in the `app/Temporal` folder instead of the root? In bigger projects that's a good separation because you can instantly see it's Temporal-related, especially if you have `Actions` and other Laravel layers in the root.

Currently:

![Screenshot_1](https://github.com/keepsuit/laravel-temporal/assets/37669560/0b22b49f-53c6-4447-8da9-4c40f99de74f)

It could have been:

![Screenshot_2](https://github.com/keepsuit/laravel-temporal/assets/37669560/5a6ddfc3-2e95-4b74-af30-280566f67c76)

**Comment by cappuc** [comment]
Yes it makes sense to group Workflows and Activities under a Temporal namespace.

For autodiscovery we can simply add the new namespace but for the make commands we should check if the project is using the new or the old structure and generate the class in the right namespace

**Comment by cappuc** [comment]
Hi @michael-rubel
I've added support for the `Temporal` root namespace in `0.6.9`.
If you want to use it, you just need to move existing workflows and activities to `App\Temporal\Workflows` and `App\Temporal\Activities` namespaces

**Comment by michael-rubel** [comment]
@cappuc Thanks!
