### ISSUE TITLE
Allow in config/temporal.php to over ride the WorkerFactory::class that is being used by the worker

### ISSUE THREAD

**Issue by slnw** [keepsuit/laravel-temporal#23]
WorkerFactory::class allows to define many configurations in the Temporal workflow, it's important when using this package that a user can easily extend the WorkerFactory class and make changes as necessary.

Another option is to allow to change the default Worker command in WorkCommand:
```php
            ...['-o', sprintf('server.command=%s ./vendor/bin/roadrunner-temporal-worker', (new PhpExecutableFinder())->find())],
```
add here an option to override the roadrunner-temportal-worker path.

**Comment by cappuc** [comment]
What options do you need to customize?

I prefer not to add too much complexity so for simple things we can add options to config file and for more advanced use cases we can allow to override the command path

**Comment by slnw** [comment]
Hi, I would like to to implement the exception handling like mentioned in - https://github.com/temporalio/sdk-php/issues/103#issuecomment-823371336
