### ISSUE TITLE
Bug with serialisation of objects from activity when there are 2 types

### ISSUE THREAD

**Issue by slnw** [keepsuit/laravel-temporal#25]
Hi, a function like
```php
function activityMethod(): FooData|false
```
returns an strObject instead of FooData object.
(FooData is Spatie Data)

**Comment by cappuc** [comment]
Right now this cannot be implemented because the data converted doesn't know the types in the union (the type provided by temporal sdk is `mixed`).

To workaround this limitation I usually create a Result wrapper data object:
```php
class ActivityResult extends Data {
    public function __construct(
        public bool $success,
        public ?FooData = null,
    ) {}
}
```
