### ISSUE TITLE
Unable to find rr binary

### ISSUE THREAD

**Issue by ninetwentyfour** [keepsuit/laravel-temporal#29]
Trying to start `temporal:work` I'm getting the warning

"Your RoadRunner binary version may be incompatible with laravel temporal."

And then the worker exits. Tracking it down a bit it seems that its unable to find the rr binary.

I've checked and it does exist in `vender/bin` is there a permission error or something I'm missing?

**Comment by cappuc** [comment]
The `rr` binary in `vendor/bin` is the roadrunner cli tool that allows to download the correct binary.
You should run `vendor/bin/rr get-binary` to download the rr binary and then run `temporal:work`.

I should update the docs.

**Comment by ninetwentyfour** [comment]
That worked perfectly! Thank you!
