### ISSUE TITLE
Temporal mock workflow unable to be picked up during test

### ISSUE THREAD

**Issue by EricxStone** [keepsuit/laravel-temporal#35]
I try to mock a workflow and test it with test utility. However, the mock workflow seems to be not being picked up.

My test file:
```php
use WithTemporal;

public function setUp(): void
{   
        parent::setUp();

}

/**
 * @test
 * /
public function test_function():
{
        Temporal::fake();
        $myWorkflowMock = Temporal::mockWorkflow(MyWorkflowInterface::class)
            ->onTaskQueue('default')
            ->andReturn('result');

        $myService = app(MyServiceInterface::class);
        $myService->start();

        $myWorkflowMock->assertDispatched();
}
```

My service function:
```php
public function start(): string
{
        $workflowStub = Temporal::newWorkflow()
            ->withRetryOptions(
                RetryOptions::new()->withMaximumAttempts(1)
            )
            ->build(MyWorkflowInterface::class);

        $workflow = app(WorkflowClient::class)
            ->start($workflowStub);

        return $workflow->getExecution()->getID();
}
```

When I dump `$workflow->getExecution()` in my service function, I am able to get an execution ID and workflow ID. However, my test is failing and saying the workflow is not dispatched. Looks like the original workflow is still getting dispatched.

Is there anyway to debug this?

**Comment by cappuc** [comment]
Hi @EricxStone,

When mocking a workflow it will not run and it returns the provided output without reaching the temporal server.

I think the problem is is the start call:
```php
$workflow = app(WorkflowClient::class)->start($workflowStub);
```
which should be replaced with:
```php
$workflow = app(WorkflowClientInterface::class)->start($workflowStub);
```

because in order to mock a workflow execution we bind a `FakeWorkflowClient` to `WorkflowClientInterface` but if you start the workflow with the original client it will start the workflow and is not intercepted.

> [!NOTE]
> In the 1.0 release you can call `Temporal::workflowClient()` to get the right client and prevent this error

**Comment by cappuc** [comment]
When you mock a workflow, it's never executed so activities inside it are not executed as well.
Mocking a workflows allows to run tests faster because it doesn't require a running temporal server (you don't need the `WithTemporal` trait when mocking a workflow).

The activity mock is used only when workflow is executed normally.
 It is very useful, for example, when the activity should be executed from another service

**Comment by EricxStone** [comment]
May I know if I mock an activity, can I run the workflow from another
service? (If I don't mock the workflow)

Or do I have to create and start the workflow inside the test in order for
the mock activity to be picked up?

**Comment by cappuc** [comment]
Mocks are global so you can start the workflow from anywhere.
But of course you have to call `Temporal::fake` and mock the activity before the workflow is created

**Comment by EricxStone** [comment]
Hey @cappuc , I am still encountering the same issue but try to ask the question again as we have more understanding on how Temporal works now.

What I try to test is the workflow logic so I am mocking the activities. I am using `WithTemporal` to start the testing server and worker and both seems starting ok. However, I found that my activity is never mocked because I can see from the logs that the actual activity is being called, plus it has encountered SQL connection error which is also strange.

This is how my test file looks like:
```php

use Keepsuit\LaravelTemporal\Facade\Temporal;
use Keepsuit\LaravelTemporal\Testing\WithTemporal;

class Test extends TestCase
{
    use WithTemporal;

    protected function setUp(): void
    {
           parent::setUp();
    }
    
    /** @test */
    public function test_function()
    {
          Temporal::mockActivity([ActivityInterface::class, 'activityFunction']);

          $workflow = Temporal::newWorkflow()->build(MyWorkflowInterface::class);
          Temporal::workflowClient()->start($workflow);
    }
}
```

Is there anything that I have missed?

I am using lib `v1.0.0`

**Comment by cappuc** [comment]
Strange it should work with this setup.

What logs are you looking at? Is it a log printed inside the activity or the temporal dashboard execution log?

**Comment by EricxStone** [comment]
It's a log printed in the activity, anyway I could further troubleshoot this?

**Comment by cappuc** [comment]
Some things you can check are:
- In the workflow the activity is built calling the interface (eg. `ActivityInterface::class` or the concrete class (eg. `Activity::class` witch implements `ActivityInterface::class`)? You should use the interface here like in the mock call.
- The activity is dispatched in the default queue? If not you should add the call to `onTaskQueue` when mocking the activity.

If nothing works you can try to edit the vendor classes to debug where is the problem, the activity mock is checked inside `FakeActivityStub::execute`

**Comment by EricxStone** [comment]
Yup the activities are build from the interface and we are using default task queue. Thanks and I will check `FakeActivityStub::execute` and see what has happened.
