### ISSUE TITLE
Worker options

### ISSUE THREAD

**Issue by slnw** [keepsuit/laravel-temporal#38]
hi,
is there a way to change the settings in the worker option without rewriting the worker roadrunner-temporal-worker process?
https://github.com/temporalio/sdk-php/blob/8cdcc1819be60e838d5e1f92b69f913aac61a58e/src/Worker/WorkerOptions.php#L31
couldn't find a way to do it in the code.

**Comment by cappuc** [comment]
Hi,
right now there is no way to change the worker options but this is a feature I want to implement so I will work on it next week

**Comment by bcaliskan-thronis** [comment]
Hi,

What about the `logger:` argument of `$factory->newWorker()` call? How do I pass a custom Logger there without changing the vendor file `roadrunner-temporal-worker`?
